export const allItems = [
    { _id: 100, title: 'All Departments' },
    { _id: 101, title: 'Arts & Crafts' },
    { _id: 102, title: 'Automotive' },
    { _id: 103, title: 'Baby' },
    { _id: 104, title: 'Beauty & Personal Care' },
    { _id: 105, title: 'Books' },
    { _id: 106, title: "Boys' Fashion" },
    { _id: 107, title: 'Computers' },
    { _id: 108, title: 'Deals' },
    { _id: 109, title: 'Digital Music' },
    { _id: 110, title: 'Electronics' },
    { _id: 111, title: "Girls' Fashion" },
    { _id: 112, title: 'Health & Household' },
    { _id: 113, title: 'Home & Kitchen' },
    { _id: 114, title: 'Industrial & Scientific' },
    { _id: 115, title: 'Kindle Store' },
    { _id: 116, title: 'Luggage' },
    { _id: 117, title: "Men's Fashion" },
    { _id: 118, title: 'Movies & TV' },
    { _id: 119, title: 'Music, CDs & Vinyl' },
    { _id: 120, title: 'Pet Supplies' },
    { _id: 121, title: 'Prime Video' },
    { _id: 122, title: 'Software' },
    { _id: 123, title: 'Sports & Outdoors' },
    { _id: 124, title: 'Tools & Home Improvement' },
    { _id: 125, title: 'Toys & Games' },
    { _id: 126, title: 'Video Games' },
    { _id: 127, title: "Women's Fashion" },
];
